name: Create PDF
on:
  push:
    branches:
      - "main"
jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: yarn --frozen-lockfile
      - run: yarn workspace blog run build
      - run: yarn workspace blog run start &>/dev/null &
      - run: PORT=3000 yarn workspace blog run generate-resume
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: github-action/create-resume-pdf
          file_pattern: packages/blog/public/resume/**.pdf
