name: Create PDF
on:
  push:
    branches:
      - "main"
jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn workspace resume install --immutable
      - run: yarn workspace resume run build
      - run: yarn workspace resume run start &>/dev/null &
      - run: PORT=9000 yarn workspace resume run print
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: github-action/create-resume-pdf
          file_pattern: packages/resume/public/resume/**.pdf
