name: Create PDF
on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run build
      - run: npm run serve &>/dev/null &
      - run: PORT=9000 npm run generate-resume
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: github-action/create-resume-pdf
          file_pattern: src/**/*.pdf